### ISSUE TITLE
Error in unmute video

### ISSUE THREAD

**Issue by crazycoder-io** [daily-co/react-native-daily-js-playground#5]
I tried the build the app, while I was building the app I did not get any error.

In working time I tried to enable my front camera it throws me this error;

` TypeError: cannot set property 'enabled' of undefined`

It is same when I try to enable rear camera.
Tested both on IOS and Android, the status same.

Can somebody help me? 
Because I got some issue on my own project too!

**Comment by filipi87** [comment]
Hi @crazycoder-io,

If you just clone our github project, install the dependencies, and execute the project, are you able to face this issue ?

If that is the case, It would be great if you could provide:
- Android version
- Device model
- Enable the debug logs. You can uncomment these lines inside the `index.js` in order to do that. 
```
// Enable debug logs
window.localStorage = window.localStorage || {};
window.localStorage.debug = '*';
window.localStorage.getItem = (itemName) => {
  console.log('Requesting the localStorage item ', itemName);
  return window.localStorage[itemName];
};
```
- Collect the logs and share with us.

If you are changing something inside the example app, in order for this issue to happen, It would be great if you could provide a code snippet, so we can understand how we can replicate this issue.

**Comment by crazycoder-io** [comment]
Thank you @filipi87.
I removed the repository that I had downloaded from Github named `react-native-daily-js-playground` and re-downloaded it again.
I cleaned both this repository’s cache and our project's cache and luckily I was able to get build. 
I don't know the exact reason what was the issue, it might be the local hermes version or flipper but once I cleaned the cache it has gone!

🥳
